### ISSUE TITLE
How to handle “didReceiveIncomingCall” method for missed call in Sinch iOS SDK?

### ISSUE THREAD

**Issue by iOS0340** [sinch/ios-simple-voice-app-tutorial#3]
When the app is in the background and an incoming call has happened and the user didn't pick up. When the user gets back into the app **`- (void)client:(id<SINCallClient>)client didReceiveIncomingCall:(id<SINCall>)call`** is being invoked. 

Is there any way to differentiate **Normal call** and **Missed call** in `didReceiveIncomingCall` method?

**Comment by spacedsweden** [comment]
Hi, didREcieve incming call is only a valid call, now we also support callkit so you should get the missed call in your callhistory
